# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aa951a30b0529773758dad5aede4c153cbb452d3e6b3789885f8132759228c09fa3c0055b79bce0bcbdebcfb2b3ac47e960ac2a2869ec1053b88c08b9ca5fa2

test:
  secret_key_base: 3eace959af2e6fb7cb1ae9ccc800227a2e602b71f2aaaace5187d337e405051353d8699e5e311b8ab950779cb648002e87af4e09ad0481d957fe789ea5333024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
